xcopy E:\xixia\PKG\j25\pkg_weblinks\com_weblinks\weblinks.xml D:\xixia\PKG\j25\pkg_weblinks\com_weblinks\weblinks.xml /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\com_weblinks\admin\models\forms\weblink.xml D:\xixia\PKG\j25\pkg_weblinks\com_weblinks\admin\models\forms\weblink.xml /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\com_weblinks\admin\sql\install.mysql.utf8.sql D:\xixia\PKG\j25\pkg_weblinks\com_weblinks\admin\sql\install.mysql.utf8.sql /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\com_weblinks\admin\views\weblink\tmpl\edit.php D:\xixia\PKG\j25\pkg_weblinks\com_weblinks\admin\views\weblink\tmpl\edit.php /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\com_weblinks\site\models\forms\weblink.xml D:\xixia\PKG\j25\pkg_weblinks\com_weblinks\site\models\forms\weblink.xml /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\com_weblinks\site\views\category\tmpl\default_items.php D:\xixia\PKG\j25\pkg_weblinks\com_weblinks\site\views\category\tmpl\default_items.php /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\mod_weblinks\mod_weblinks.xml D:\xixia\PKG\j25\pkg_weblinks\mod_weblinks\mod_weblinks.xml /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\plg_finder_weblinks\weblinks.xml D:\xixia\PKG\j25\pkg_weblinks\plg_finder_weblinks\weblinks.xml /I /Y /E
xcopy E:\xixia\PKG\j25\pkg_weblinks\plg_search_weblinks\weblinks.xml D:\xixia\PKG\j25\pkg_weblinks\plg_search_weblinks\weblinks.xml /I /Y /E
